// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: api/vote_service.proto

package vote_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteResponse_VoteStatus int32

const (
	VoteResponse_Accepted  VoteResponse_VoteStatus = 0 // The vote was accepted
	VoteResponse_Cancelled VoteResponse_VoteStatus = 1 // The vote was cancelled
)

// Enum value maps for VoteResponse_VoteStatus.
var (
	VoteResponse_VoteStatus_name = map[int32]string{
		0: "Accepted",
		1: "Cancelled",
	}
	VoteResponse_VoteStatus_value = map[string]int32{
		"Accepted":  0,
		"Cancelled": 1,
	}
)

func (x VoteResponse_VoteStatus) Enum() *VoteResponse_VoteStatus {
	p := new(VoteResponse_VoteStatus)
	*p = x
	return p
}

func (x VoteResponse_VoteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteResponse_VoteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_vote_service_proto_enumTypes[0].Descriptor()
}

func (VoteResponse_VoteStatus) Type() protoreflect.EnumType {
	return &file_api_vote_service_proto_enumTypes[0]
}

func (x VoteResponse_VoteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteResponse_VoteStatus.Descriptor instead.
func (VoteResponse_VoteStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_vote_service_proto_rawDescGZIP(), []int{1, 0}
}

type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CypherVote []byte `protobuf:"bytes,2,opt,name=cypher_vote,json=cypherVote,proto3" json:"cypher_vote,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vote_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vote_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_api_vote_service_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VoteRequest) GetCypherVote() []byte {
	if x != nil {
		return x.CypherVote
	}
	return nil
}

type VoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status VoteResponse_VoteStatus `protobuf:"varint,1,opt,name=status,proto3,enum=vote_service.VoteResponse_VoteStatus" json:"status,omitempty"`
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vote_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vote_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_api_vote_service_proto_rawDescGZIP(), []int{1}
}

func (x *VoteResponse) GetStatus() VoteResponse_VoteStatus {
	if x != nil {
		return x.Status
	}
	return VoteResponse_Accepted
}

var File_api_vote_service_proto protoreflect.FileDescriptor

var file_api_vote_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x79, 0x70, 0x68, 0x65, 0x72, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x63, 0x79, 0x70, 0x68, 0x65, 0x72, 0x56, 0x6f, 0x74, 0x65, 0x22, 0x78, 0x0a,
	0x0c, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e,
	0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a, 0x0a,
	0x56, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x32, 0x64, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x19,
	0x2e, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x6f, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x3a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x42, 0x0f, 0x5a,
	0x0d, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_vote_service_proto_rawDescOnce sync.Once
	file_api_vote_service_proto_rawDescData = file_api_vote_service_proto_rawDesc
)

func file_api_vote_service_proto_rawDescGZIP() []byte {
	file_api_vote_service_proto_rawDescOnce.Do(func() {
		file_api_vote_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_vote_service_proto_rawDescData)
	})
	return file_api_vote_service_proto_rawDescData
}

var file_api_vote_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_vote_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_vote_service_proto_goTypes = []interface{}{
	(VoteResponse_VoteStatus)(0), // 0: vote_service.VoteResponse.VoteStatus
	(*VoteRequest)(nil),          // 1: vote_service.VoteRequest
	(*VoteResponse)(nil),         // 2: vote_service.VoteResponse
}
var file_api_vote_service_proto_depIdxs = []int32{
	0, // 0: vote_service.VoteResponse.status:type_name -> vote_service.VoteResponse.VoteStatus
	1, // 1: vote_service.VoteService.Vote:input_type -> vote_service.VoteRequest
	2, // 2: vote_service.VoteService.Vote:output_type -> vote_service.VoteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_vote_service_proto_init() }
func file_api_vote_service_proto_init() {
	if File_api_vote_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_vote_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vote_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_vote_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vote_service_proto_goTypes,
		DependencyIndexes: file_api_vote_service_proto_depIdxs,
		EnumInfos:         file_api_vote_service_proto_enumTypes,
		MessageInfos:      file_api_vote_service_proto_msgTypes,
	}.Build()
	File_api_vote_service_proto = out.File
	file_api_vote_service_proto_rawDesc = nil
	file_api_vote_service_proto_goTypes = nil
	file_api_vote_service_proto_depIdxs = nil
}
